### ISSUE TITLE
Classes in SDL-Images not found in Xcode iOS project

### ISSUE THREAD

**Issue by alanpoon** [tanis2000/minigame-rust#5]
After I've built libSDL.a using SDL-mirror's iso-build.sh, I copied build-scripts/platform/x86_64_sim/lib/libSDL2.a to minigame/target/x86_64_apple_ios/debug. I cargo build it with "cargo build --no-default-features --target x86_64-apple-ios --lib".
I opened the xcodeproject, and ran it, I have many classes in SDL-Images not found. 

Undefined symbols for architecture x86_64:
  "_IMG_isXV", referenced from:
      _$LT$sdl2..rwops..RWops$LT$$u27$a$GT$$u20$as$u20$sdl2..image..ImageRWops$GT$::is_xv::h8a58129ea221ea0d in libminigame.a(sdl2-d5cee32acb9421b0.0.o)

I couldn't figure what went wrong, I should believe that libSDL2.a in the SDL-mirror should have all other features like ttf, and audio and images.

Please advise, thanks.

**Comment by tanis2000** [comment]
The iOS project was left behind compared to the current state of the art of the Rust code. 
I've just pushed a commit that should fix it for you as well: https://github.com/tanis2000/minigame-rust/commit/c60307eb2214a2f3c54329e9d22248c6ea37a7f0

Make sure that you have `libSDL2_image.a` in your target/[platform] folder because libSDL2.a does not include image, ttf, etc...

**Comment by alanpoon** [comment]
Thanks,
The [SDL2.0 website](https://www.libsdl.org/projects/SDL_image/#source ) says "unpack and build", but didn't say how to build it. Can you tell me how to build it?

**Comment by tanis2000** [comment]
Sorry, I completely overlooked your answer. It's usually just a matter of running:

```
./configure
make
```

from within the SDL2_image folder.
