### ISSUE TITLE
Gif or static screenshot in README.md?

### ISSUE THREAD

**Issue by ip** [tanis2000/minigame-rust#6]

**Comment by tanis2000** [comment]
Sounds like a good idea.. I'll add one as soon as I get this back into a proper working state ;)

**Comment by tanis2000** [comment]
I've added a screenshot in the `entity` branch which is the one I'm working on at the moment.
You can check it out there: https://github.com/tanis2000/minigame-rust/blob/entity/README.md

@coder543 the code itself works but it's a bit of a mess as I'm basically using this project to experiment with various design patterns and trying to build some tools.

I'm actually trying to find a good design architecture so that I could have a tool that takes care of creating a game template that uses this as the base engine and that can compile to all the different platforms. It's not that easy though as there are a lot of parts involved and I could definitely use some help.
